### ISSUE TITLE
[Bug]: Impossible to launch the UI

### ISSUE THREAD

**Issue by MehdiHa12** [EmpireMediaScience/A1111-Web-UI-Installer#75]
### Have you read the readme, especially the Warning part ?

- [X] I have read the readme, especially the Warning Part

### Did this problem occur before the "commit hash:" line in the log ?

- [X] I swear that this problem occurred before the "commit hash:" line in the log, and that if it has instead occured after, I owe the devs a $10.000 donation.

### Are you up to date ?

- [X] I have the latest version of the launcher

### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent release

### What happened?

Hello, 

I installed A1111 through the installer about a month and a half ago, I had a few bugs here and there that made me do a new clean install but nothing too bad.

However, since a few days ago, I have a big problem, when I launch the launched, it just immediatly closes back, no matter what I do.
I tried a clean install and everything, nothing seems to be working...

The only thing I did on the PC before that was installing a video game 

Any ideas what the problem could be ?

### Steps to reproduce the problem

1. Launching the launcher
2. The launcher immediatly closes after opening (no lines of code)

### What should have happened?

It should just launch normally

### Version of the Installer/Launcher where the problem happens

1.7.0

**Comment by MehdiHa12** [comment]
> Try to go into the launcher folder and right click launcherUI.ps1 => Run with Powershell, if that works it's because the shortcut is wrong, you may have changed the path of the launcher, by either moving the folders or renaming them in some way

It now goes a little further but crashes when it's right after the Update Web UI line...

**Comment by Mozoloa** [comment]
Can I get some logs ? or a screen recording of what happens ? else I can't guess what's happening

**Comment by Mozoloa** [comment]
When the UI launches there's also a powershell terminal that opens on the side, there's two windows for the program, you'll find the log there, if it closes to fast, try to record the terminal on your screen with obs or share x, while it glitches out.

**Comment by Dream552b** [comment]
May I ask if this problem has been solved? I also met this problem. Request answer

**Comment by Mozoloa** [comment]
Without any log or sight of what happens precisely I can't fix anything

**Comment by Mozoloa** [comment]
This issue has been dead so I guess it was resolved, reopen if needed

**Comment by MehdiHa12** [comment]
Sorry, it’s not resolved, I will post the screen records tomorrow

I haven’t had the time to do it last week

Le mar. 16 mai 2023 à 20:58, Leo Mozoloa ***@***.***> a
écrit :

**Comment by Mozoloa** [comment]
Thanks !

**Comment by robotdob** [comment]
I just started having this issue as well, after UI and extensions check for updated this flashes then closes. I was able to keep it from holding a click on the titlebar but the terminal is unresponsive. 
<img width="865" alt="WindowsTerminal_lfmkleZWg0" src="https://github.com/EmpireMediaScience/A1111-Web-UI-Installer/assets/21193372/4c38035b-c377-4d83-bac1-3c767f77c70d">

**Comment by telzhou618** [comment]
@MehdiHa12 

I have the same problem,I solved it like this:

1. open in terminal by right click on the desktop.
2. open settings.
3. select startup, update default terminal application to "Windows Console Hot", do not use "Windows Terminal"!!!
4. run "A1111 WebUI (Pin to Taskbar)" again, it is ok.

**Comment by robotdob** [comment]
> @MehdiHa12
> 
> I have the same problem,I solved it like this:
> 
> 1. open in terminal by right click on the desktop.
> 2. open settings.
> 3. select startup, update default terminal application to "Windows Console Hot", do not use "Windows Terminal"!!!
> 4. run "A1111 WebUI (Pin to Taskbar)" again, it is ok.
> 
> my os is win11.

This was the issue! Thanks for the help, I had given up on A111 before I read your response. I appreciate you sharing your resolution.

**Comment by RowanBee** [comment]
I'm having the same issue after I tried installing Powershell 7 for something unrelated. Now it just crashes immediately. I've tried the above fix, and I've tried reinstalling. I uninstalled Powershell 7, and I've tried everything I can think of.
![](https://i.imgur.com/nQXFtsj.gif)

**Comment by Mozoloa** [comment]
This project is not maintained anymore I recommend going the way of StabilityMatrix it's a way better launcher !

**Comment by gitihobo** [comment]
can you make it so the installer does it through anaconda environment and not directly in base environment?
